### ISSUE TITLE
No this packages

### ISSUE THREAD

**Issue by Roker2** [Amritorock/android_device_realme_r5x#1]
Offending entries:
SettingsProviderOverayR5x
android.hardware.audio.effect@2.0-service
android.hardware.media.omx@1.0-impl
audio.primary.trinket
fstab.qcom_ramdisk
init.recovery.qcom.rc
libdisplayconfig
libdisplayconfig.vendor
libldacBT_bco
libloc_net_iface
liblocdiagiface
build/make/core/main.mk:1374: error: Build failed.

**Comment by Roker2** [comment]
https://github.com/LineageOS/android_device_nubia_nx611j/commit/5fec8665d10d66b7064e7148062f1ba2f0fa6838

**Comment by Amritorock** [comment]
Done already
